const PREFIX = 'AUTH';
export const LOGIN 						= `${PREFIX}/LOGIN`;
export const LOGIN_SUCCESS		= `${PREFIX}/LOGIN_SUCCESS`;
export const LOGOUT 					= `${PREFIX}/LOGOUT`;
export const LOGOUT_SUCCESS		= `${PREFIX}/LOGOUT_SUCCESS`;
export const REGISTER 				= `${PREFIX}/REGISTER`;
export const RECOVER					= `${PREFIX}/RECOVER`;
export const CHECK_AUTHENTICATION = `${PREFIX}/CHECK_AUTHENTICATION`;
export const AUTHENTICATION_SUCCESS = `${PREFIX}/AUTHENTICATION_SUCCESS`;
export const VALIDATE_ACCOUNT = `${PREFIX}/VALIDATE_ACCOUNT`;
export const UPDATE_PASSWORD = `${PREFIX}/UPDATE_PASSWORD`;

export const CLEAR_AUTH = `${PREFIX}/CLEAR_AUTH`;
